### ISSUE TITLE
Dupe Guru Sqlite error at launch

### ISSUE THREAD

**Issue by eemantsal** [hsoft/portage-overlay#3]
Just installed Dupeguru 4.1 from your overlay, and I can't launch it. See the message:

```
$ dupeguru 
Traceback (most recent call last):
  File "/usr/bin/dupeguru", line 49, in <module>
    sys.exit(main())
  File "/usr/bin/dupeguru", line 35, in main
    from qt.app import DupeGuru
  File "/usr/share/dupeguru/qt/app.py", line 22, in <module>
    from core.app import AppMode, DupeGuru as DupeGuruModel
  File "/usr/share/dupeguru/core/app.py", line 24, in <module>
    from . import se, me, pe
  File "/usr/share/dupeguru/core/pe/__init__.py", line 1, in <module>
    from . import block, cache, exif, iphoto_plist, matchblock, matchexif, photo, prioritize, result_table, scanner # noqa
  File "/usr/share/dupeguru/core/pe/cache.py", line 12, in <module>
    import sqlite3 as sqlite
ImportError: No module named 'sqlite3'
```
I have Sqlite 3.13, the latest in Portage, I think.

BTW, your overlay seems not to be listed by https://gpo.zugaina.org/ so if you search for "dupeguru" you get no results and may probably think that there's no ebuild for DG. I have found this Github page a bit by chance. I think you might want to tell the people of gpo.zugaina.org about your overlay.

Regards

**Comment by hsoft** [comment]
You're right. In the 4.x transition, I accidentally dropped the `sqlite` flag req for `dev-lang/python`.

**Comment by eemantsal** [comment]
I just tried new version. Works perfectly. Thanks to you for writing such a nice and useful program. :D
