### ISSUE TITLE
Ebuild for dupeguru-se-3.8.0

### ISSUE THREAD

**Issue by jlpell** [hsoft/portage-overlay#4]
I have tried using dupeguru-se-3.8.0 to sort through backup files for unneeded redundancy, it worked rather well. Thank you for your hard work.

This week I started getting portage errors when trying to do an emerge on my system, did you change the ebuild? Do you recommend that I just unmerge "dupeguru-se" and try using the most recent "dupeguru"? 
I've included a copy of the emerge error below. Thanks again.

"
 ERROR: app-misc/dupeguru-se-3.8.0::hsoft failed (depend phase):
 *   No supported implementation in PYTHON_COMPAT.
 * 
 * Call stack:
 *                  ebuild.sh, line 606:  Called source '/var/lib/layman/hsoft/app-misc/dupeguru-se/dupeguru-se-3.8.0.ebuild'
 *   dupeguru-se-3.8.0.ebuild, line   8:  Called inherit 'dupeguru-qt4'
 *                  ebuild.sh, line 302:  Called __qa_source '/var/lib/layman/hsoft/eclass/dupeguru-qt4.eclass'
 *                  ebuild.sh, line 102:  Called source '/var/lib/layman/hsoft/eclass/dupeguru-qt4.eclass'
 *        dupeguru-qt4.eclass, line   6:  Called inherit 'eutils' 'python-r1'
 *                  ebuild.sh, line 302:  Called __qa_source '/usr/portage/eclass/python-r1.eclass'
 *                  ebuild.sh, line 102:  Called source '/usr/portage/eclass/python-r1.eclass'
 *           python-r1.eclass, line 224:  Called _python_set_globals
 *           python-r1.eclass, line 186:  Called _python_set_impls
 *     python-utils-r1.eclass, line 130:  Called die
 * The specific snippet of code:
 *   		die "No supported implementation in PYTHON_COMPAT."

"

**Comment by hsoft** [comment]
Yes, I recommend you replace `dupeguru-se` with `dupeguru`. I should remove those old packages from the repo...

**Comment by jorgicio** [comment]
The same happens here, even when I sync with eix.
A workaround is to fix the eclass file (dupeguru-qt4), to remove the python3_3 support and use python3_{4,5} instead.
