### ISSUE TITLE
vimb: libsoup  soup_uri_encode

### ISSUE THREAD

**Issue by zlice** [hsoft/portage-overlay#5]
command line
(vimb:27661): libsoup-CRITICAL **: soup_uri_encode: assertion 'part != NULL' failed

browser
"Webview Crashed on <url>"

have the webkit and libsoup on gentoo

libsoup-2.56.0:2.4
webkit-gtk-2.16.3:4/37

another weird thing that happens, any input field doesn't go to "INPUT" or "INSERT" mode and typing something like 'f' puts a ":o" and 'o' tries to open a url ':open '

what are you running where vimb works for gentoo?

**Comment by hsoft** [comment]
Hum, I don't have that problem. I run on the same versions of libsoup + webkit-gtk as you.

**Comment by zlice** [comment]
must have something to do with how i screwed up my system. didn't update for months and blotched most of my packages trying to update...i should probably do a fresh install =/ but i'm not sure that i have the time. thanks

**Comment by zlice** [comment]
re-did my system, looks to work, issue was on my end
